### ISSUE TITLE
Priority: High: ActivateConditional issue with Nested questions on resetting State

### ISSUE THREAD

**Issue by st59** [openanthem/nimbus-core#393]
Associated with F/W version 1.1.11
Description:
When user answers ‘Yes’ to V1, it activates set of questions V2,V3.. from ‘nested’ group. If user enters some value in V2 and then user changes answer of V1 to ‘No’, it is hiding the ‘nested’ group of questions and then, if user answers ‘Yes’ to V1, it is activating ‘nested’ group of questions with V2 filled with previously entered value on last activated instance. The same value is also persisted in DB.

Expected: The state associated with the nested group of questions should be reset on deactivating. The state should also be reset in database.

Code Snippets:

View:
 @MapsTo.Type(SampleCore.class)
       @Getter
       @Setter
       public static class VFForm {
              @Radio(postEventOnChange=true)
              @Model.Param.Values(YNType.class)
              @Label("Test1")
              @ActivateConditional(when="state=='Yes'",targetPath= {"/../nested"})
              @Path
              private String V1;
              
              @FormElementGroup
              private Nested nested;      
       }
       
       @MapsTo.Type(SampleCore.class)
       @Getter
       @Setter
       public static class Nested{ 
              @TextBox(postEventOnChange=true)
              @Label("Test2")
              @Path
              private String V2;
       }

Core:
public class SampleCore extends IdLong {
       private static final long serialVersionUID = 1L;
       private String v1;
       private String v2;
}

Junit Test Case:
   @Test
    public void t0_activateConditionalTest() {
             
              MockHttpServletRequest viewReq = MockHttpRequestBuilder.withUri("x/y/p/sampleview")
                           .addAction(Action._new).getMock();
              Holder<MultiOutput> holderView = (Holder<MultiOutput>)controller.handlePost(viewReq, null);
              MultiOutput viewResponse = holderView.getState();
              Param<?> viewParam = (Param<?>)viewResponse.getSingleResult();
              assertNotNull(viewParam);
              String questionPath = "/vpPage/vtTile/vsSection/vfForm";    
              assertFalse((Boolean) viewParam.findParamByPath(questionPath+"/nested/v2").isVisible());
             
              //set v1 to "Yes"
              viewParam.findParamByPath(questionPath+"/v1").setState("Yes");
              //Check if v2 is visible
              assertTrue((Boolean) viewParam.findParamByPath(questionPath+"/nested/v2").isVisible());
              //Set v2 to "Test"
              viewParam.findParamByPath(questionPath+"/nested/v2").setState("Test");
              //Set v1 to "No"
              viewParam.findParamByPath(questionPath+"/v1").setState("No");
              //Check if v2 is hidden
              assertFalse((Boolean) viewParam.findParamByPath(questionPath+"/nested/v2").isVisible());
              //Check if v2 is set to null
              assertEquals(null,viewParam.findParamByPath(questionPath+"/nested/v2").getState());
       }

**Comment by dileeproopreddy** [comment]
This issue is seen in F/W version 1.1.9 as well.
