### ISSUE TITLE
Accordiantab style behaving differently when open and close mode

### ISSUE THREAD

**Issue by balukaliannan** [openanthem/nimbus-core#407]
If the page contains mutilple accorian tabs, one of the Accordiantab style behaving differently when open and close mode.

Behaviour : when the Accordiantab is opened , the overflow style is true if it contains form.
when the Accordiantab is closed , the overflow style is true if it contains form and also creating blank space at the end of footer page.

 
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
 when the Accordiantab is opened , the overflow style is true if it contains form.
when the Accordiantab is closed , the overflow style is true if it contains form and also creating blank space at the end of footer page.

## Expected Behavior
 when the Accordiantab is opened or closed  ,it should not  create blank space at the end of footer page.

### Code Snippet

# Environment Details
* **Nimbus Version:**
1.1.11

* **Browser:**
Chrome , version: Version 72.0.3626.109

**Comment by BruceBarta** [comment]
nimbus-sass-module "version": "1.18.34" provided fix for accordion closed height issue
added .card-holder {overflow: hidden} to constrain visible content within parent container
