### ISSUE TITLE
Team Library - Add program: Modal window is moving up and down when adding programs

### ISSUE THREAD

**Issue by zzyed** [openanthem/nimbus-core#416]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Every time a program is selected, the modal window moves up or down

## Expected Behavior
No movement of the modal window

### Steps to Reproduce

1. Log into application as client admin
2. Navigate to team library page and add a team
3. While adding a new team - do not add any programs yet
4. After a team is created without a program(s) click on edit team
5. Now select add program while editing team
6. Modal window opens for adding programs

### Code Snippet

# Environment Details
* **Nimbus Version:**
v1.2

* **Browser:**
chrome

**Comment by lopezton-anthem** [comment]
> Every time a program is selected, the modal window moves up or down

What is a program?

Can you please include sample code to recreate the issue in a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve)?
