### ISSUE TITLE
Submit Button is Enabled By Default and Required Asterisk is Disappearing After Selection is Made

### ISSUE THREAD

**Issue by DROB1979** [openanthem/nimbus-core#417]
# Issue Details

**Type of Issue**  (check one with "X")
```
[x ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior

Submit button is enabled without user making a selection of a Required Field and Required Field asterisk disappears after user makes a selection.

## Expected Behavior

The Submit button should not be enabled until the user makes a selection for a Required Field and the asterisk should still display after the user has made that selection.

### Steps to Reproduce

1) Log into the application

2) Navigate to page

3) Click menu entry that brings you to page containing Required Fields with asterisk

4) Select a value from available options in Required Field

### Code Snippet

# Environment Details
* **Nimbus Version:**

* **Browser:**

Firefox, Edge, Chrome

**Comment by lopezton-anthem** [comment]
There is missing detail in this issue. Please add more detail for us to understand the issue and why it is happening including:

* version
* code snippet with a brief explanation of any other steps that are taken before this scenario is occurring. (e.g. are there any rule files that are attempting to toggle the enabled property of a param, visibility, etc)

More details on providing concrete examples can be found here: https://stackoverflow.com/help/mcve
