### ISSUE TITLE
Tooltip or Modal for Specialty Product Icons

### ISSUE THREAD

**Issue by kkrickus** [openanthem/nimbus-core#424]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[x ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior

Specialty Product Icons are now aligned in a single row but need to show details for each icon (phone number for 4 of the icons and phone number + 2 other data elements for the EAP icon) when clicked or hovered over. 

## Expected Behavior

<img width="366" alt="screen shot 2019-03-04 at 10 11 21 am" src="https://user-images.githubusercontent.com/48034040/53742216-22074980-3e66-11e9-8a3a-84bb5bf8128a.png">

Would prefer a tooltip to display this data but would be open to a modal window if that is easier/quicker to implement. Or would be open to having a screen that displays all the details for the specialty programs the member is eligible for.

### Code Snippet

VsCaseHeader.java

@Model
	@MapsTo.Type(CMCase.class)
	@Getter
	@Setter
	public static class FieldGroup_CardBodyCase2 {

		@FieldValue(cols = "1", showName = true, cssClass = "label-left align-right")
		@Path(linked = false)
		@Label(value = "Case Owner")
		private String caseOwner;

		@FieldValue(cols = "1", showName = true, cssClass = "label-left align-right")
		@Path(linked = false)
		@Label(value = "Program Status")
		private String caseIs;

		@FieldValue(cols = "1", showName = true, cssClass = "label-left align-right")
		@Path("/status")
		@Label(value = "Case Status ")
		private String caseStatus;

//		@FieldValue(cols = "1", showName = true, cssClass = "label-left align-right")
//		@Label(value = "Specialty Products ")
//		private String specialtyProducts;
		
		@FieldValue(cols = "2", showName = true, cssClass = "col-sm-6 text-sm-right hide-value")
		@Label(value = "Specialty Products ")
		private String specialtyProducts;		

		// commented below code due to framework limitation to align the images in single line.
		// In future, when framework supports it can be uncommented.
		// below are the images to be shown.
		@ActivateConditional(when = "state != null", targetPath = { "../dental" })
		@Path(linked=false)
		@Label(" ")
		@FieldValue(applyValueStyles=true, cols="5", showName=false, cssClass = "inline")	
		private String dental;

		@ActivateConditional(when = "state != null", targetPath = { "../vision" })
		@Path(linked=false)
		@Label(" ")
		@FieldValue(applyValueStyles=true, cols="5", showName=false, cssClass = "inline")
	    private String vision;

		@ActivateConditional(when = "state != null", targetPath = { "../medical" })
		@Path(linked=false)
		@Label(" ")
		@FieldValue(applyValueStyles=true,  cols="5", showName=false, cssClass = "inline")
		private String medical;
		
		@ActivateConditional(when = "state != null", targetPath = { "../disability" })
		@Path(linked=false)
		@Label(" ")
		@FieldValue(applyValueStyles=true,  cols="5", showName=false, cssClass = "inline")
		private String disability;
		
		@ActivateConditional(when = "state != null", targetPath = { "../eap" })
		@Path(linked=false)
		@Label(" ")
		@FieldValue(applyValueStyles=true,  cols="5", showName=false, cssClass = "inline")
		private String eap;

	}

# Environment Details
* **Nimbus Version:**

2.0.0

* **Browser:**

Chrome

**Comment by lopezton-anthem** [comment]
Are you able to achieve this using `@Label`'s `helpText` attribute? I believe this should generate a tool tip:

```java
@ActivateConditional(when = "state != null", targetPath = { "../dental" })
@Path(linked=false)
@Label(value = " ", helpText = "888-888-8888")
@FieldValue(applyValueStyles=true, cols="5", showName=false, cssClass = "inline")	
private String dental;
```

**Comment by kkrickus** [comment]
If I add the “helpText” attribute to the Specialty Product label then it shows the ? icon and the text after clicking the ? icon, but then the specialty icons don’t display:

[cid:image001.png@01D4D2B4.53E77150]


If I add the “helpText” attribute to the icon fields, for instance, “@Label(value = " ", helpText = "Dental")”, then neither the ? icon nor the help text displays:

[cid:image002.png@01D4D2B4.53E77150]


Anthem, Inc.



Karen Krickus, Solution Engineer Advisor Sr, CCE – CM/DM
2221 Edward Holland Dr, Richmond, Virginia 23230
karen.krickus@anthem.com<mailto:karen.krickus@anthem.com>

**Comment by lopezton-anthem** [comment]
To support this, I think we need to add the ability to pass the HTML `title` attribute through. SpEL support is given, but I don't think Command DSL Query execution is given.  To display your data (e.g. phone number, or other information... is this data belonging to the state of another param?)

**Comment by kkrickus** [comment]
The rule is “loadMemberCaseBanner.drl” where the state is set in Member.memberPlan. However I will need to add the additional details to this… right now it just states if the member has eligibility for a particular specialty product.

Here is the code:


       // commented below code due to framework limitation to align the images in single line.

       // In future, when framework supports it can be uncommented.

       /*     List<CoveragePlan> memberPlan = (List<CoveragePlan>) $core.findStateByPath("/.m/memberPlan");

              if(memberPlan != null)

              {

                     for(CoveragePlan plan : memberPlan)

                     {

                           if(plan==null)

                                  continue;



                           if("dental".equalsIgnoreCase(plan.getPlanId()))

                           {

                                  $core.findParamByPath("/../fgCardBodyCase2/dental").setState("dental");

                           }

                           else if("medical".equalsIgnoreCase(plan.getPlanId()))

                           {

                                  $core.findParamByPath("/../fgCardBodyCase2/medical").setState("medical");

                           }

                           else if("vision".equalsIgnoreCase(plan.getPlanId()))

                           {

                                  $core.findParamByPath("/../fgCardBodyCase2/vision").setState("vision");

                           }

                           else if("disability".equalsIgnoreCase(plan.getPlanId()))

                           {

                                  $core.findParamByPath("/../fgCardBodyCase2/disability").setState("disability");

                           }

                     }

              }*/


Anthem, Inc.



Karen Krickus, Solution Engineer Advisor Sr, CCE – CM/DM
2221 Edward Holland Dr, Richmond, Virginia 23230
karen.krickus@anthem.com<mailto:karen.krickus@anthem.com>

**Comment by lopezton-anthem** [comment]
This scenario should be able to be supported by a `@Modal` implementation.

I have also created [NIMBUS-136](https://anthemopensource.atlassian.net/browse/NIMBUS-136) to support the `title` attribute; however it will need to be validated and approved before work begins on it.  Just creating the issue as a placeholder for support should we need to add it in the future.

**Comment by lopezton-anthem** [comment]
After looking more closely at this specific scenario, the use case is using a `@FieldValueGroup`, which doesn't display `@Link` components.

I would suggest we either need to modify the business need, or wait until the work for [NIMBUS-136](https://anthemopensource.atlassian.net/browse/NIMBUS-136) is complete.
