### ISSUE TITLE
PGM_Supervisor user is able to delete roles for users.

### ISSUE THREAD

**Issue by rakesharrolla** [openanthem/nimbus-core#451]
# Issue Details
PGM_Supervisor user is able to delete roles for users.

## Jira Link: Please see for detail explanation of the issue
** Jira ticket no : IRXPGM-2856**

**Type of Issue** 
Functional Issue

## Current Behavior
Grid Should be enabling along with Delete button

## Expected Behavior
Grid Should be disable along with Delete button

### Code Snippet
 N/A

# Environment Details
* **Nimbus Version:**

nimbus.framework.version -->1.3.0.M2

* **Browser:**
Chrome

**Comment by lopezton-anthem** [comment]
Closing due to inactivtiy.
