### ISSUE TITLE
Menu items should not be displayed as LHS navigation for secondary pages

### ISSUE THREAD

**Issue by PragneshHadiyel** [openanthem/nimbus-core#456]
For Nimbus based application, if menu item is added in second page of the application(not the landing page), by default it is showing as left nav menu bar. It is supposed to show on top with horizontal menus(this works absolutely fine if it is added on landing page), this is a critical requirement for us to proceed, please fix/share the workaround.

Contact for further discussion.

**Comment by sandeepmantha** [comment]
Please create a feature request for the menu panel to accept a css class that aligns it accordingly

**Comment by lopezton-anthem** [comment]
@PragneshHadiyel, on which version of the framework are you on?

**Comment by PragneshHadiyel** [comment]
Issues is there in all versions till 1.3. We are using 1.3.

**Comment by sandeepmantha** [comment]
Fix provided in 1.3 with version > 1.3.0.M5

**Comment by lopezton-anthem** [comment]
Additional changes added to `1.3.0.M5`
