### ISSUE TITLE
Data persistance with core domain @Domain value rather than @Repo alias

### ISSUE THREAD

**Issue by rajesh-bandarupalli** [openanthem/nimbus-core#459]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
When i perform /_new on a view domain and the form is mapped to the core domain and all the fields in the form are mapped and set to postEventOnChange=true, a new collection is created in mongoDB with @Domain value rather than @Repo alias. 

## Expected Behavior
It should use @Repo alias to persist the data.

### Code Snippet

```
@Domain(value = "carCore", includeListeners = {ListenerType.persistence})
@Repo(alias = "car", value = Database.rep_mongodb, cache = Cache.rep_device)
public class Car {
private String name;
}

@Domain(value = "audiCar", includeListeners = {ListenerType.persistence})
public class Audi extends Car{
private String audiModel;
}

@MapsTo.Type(Audi.class)
public class VFCar{
@Label("Car Brand")
@TextBox(postEventOnChange=true)
@Path
private String name;
}
```

# Environment Details
* **Nimbus Version:**
1.3.0.M4

* **Browser:**
Google Chrome

**Comment by lopezton-anthem** [comment]
This was introduced during the merge with the remote model repository implementation and custom model repository implementation.
