### ISSUE TITLE
Framework doesn't allow Combo-boxes to offer a  "blank" selection item

### ISSUE THREAD

**Issue by pkanthem** [openanthem/nimbus-core#481]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[X ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Some HIP NICU combo boxes do not require a value to be selected.   On update, it is currently not possible to select a blank value from the combo box.

## Expected Behavior
For combo boxes that are not required, the user should be able to select a blank value from the drop down list.

### Steps to Reproduce
Test example can be provided by the scrum team.

### Code Snippet

# Environment Details
* **Nimbus Version:**

* **Browser:**

**Comment by lopezton-anthem** [comment]
@pkanthem Who are you?  Can you message me in Sococo
