### ISSUE TITLE
Global way to disable and enable growl errors

### ISSUE THREAD

**Issue by addulaajayreddy** [openanthem/nimbus-core#491]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[X ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Showing user the errors from which they cannot make anything out of it.

## Expected Behavior
Ability to hide the Growl errors

### Steps to Reproduce
Any runtime exceptions are shown as growl errors in UI

### Code Snippet

# Environment Details
* **Nimbus Version:**
Version 1.3.0.M5

* **Browser:**
Chrome

**Comment by lopezton-anthem** [comment]
I think there is a way to support this currently, today. I don't see any documentation about how exception handling can be managed by nimbus clients, so I will add a quick synopsis here and I will get it added to the docs.  @addulaajayreddy will you please refer to this documentation below, let me know if it works for you... and if we need more granular control we can discuss further?

---

# Providing custom messages for an exception
Custom messages can be defined for exception types that bubble up from the framework or client managed beans that are caught by the global exception handler defined to catch all exceptions of type `Throwable` in `WebActionControllerAdvice` of the framework. This can easily be achieved by defining the following in the `application.yml` configuration:

```yml
application:
  exceptions:
    com.acme.foo.exceptions.MySpecialException: Some custom message here
    java.lang.NullPointerException: Something was null
```

## Reserved exception keywords
There are certain reserved keywords that when used in defining custom exception messages that will be replaced.

ERR.UNIQUEID: The unique generated error id.

# Defining a custom exception handler
The `@ExceptionHandler` defined within the framework is a catch all for all types of `Throwable` exceptions.  Custom logic can be applied by defining a `@ExceptionHandler` within a nimbus client application to return a desirable response.

```java
@Autowired
CommandTransactionInterceptor interceptor;

@ExceptionHandler(NullPointerException.class)
@ResponseBody
public ResponseEntity<MultiExecuteOutput> exception(NullPointerException exception) {
    HttpHeaders headers = new HttpHeaders();
    ExecuteOutput<?> executeOutput = new ExecuteOutput<>();
    executeOutput.setExecuteException(new ExecuteError(exception.getClass(), "Some custom message"));
    MultiExecuteOutput output = interceptor.handleResponse(executeOutput);
    return new ResponseEntity<>(output, headers, HttpStatus.INTERNAL_SERVER_ERROR);
}
```

[NOTE] `CommandTransactionInterceptor` provides some utility methods for building the expected response the UI expects for a server side error.

# Suppressing UI error messages
The UI will not render popup error messages if the error message that is returned from the server is `null` or empty. Simply set the error message to be empty to suppress a UI error message from being displayed.

**Comment by lopezton-anthem** [comment]
So for example if you wanted to suppress all FrameworkRuntimeExceptions, you could by doing:

```yaml
application:
  exceptions:
    com.antheminc.oss.nimbus.FrameworkRuntimeException:
```

**Comment by jayantchaudhuri** [comment]
I think this is a good option. It gives the ability for implementing applications to control how to render system exceptions. We can have the client application configure a generic user friendly message for FrameworkRuntimeException if the exception message is too technical for the user

**Comment by lopezton-anthem** [comment]
This will handle these exceptions "globally" in the sense that if the defined exception shows up, the message defined is what the user gets.

@addulaajayreddy 
If more granular control is needed at on a per/execution level, the `FrameworkRuntimeException` is treated as a special case in `WebActionControllerAdvice.constructExecError(Throwable pEx)`, and I think you can add some custom handling to retrieve information about the exception and decide whether or not you want to mute the message.

**Comment by lopezton-anthem** [comment]
Added documentation here: https://github.com/openanthem/nimbus-docs/commit/f44d57758fb17ff13a4f7f68c255578031976454
