### ISSUE TITLE
Filter @Grid component does not display the expected (contains) result

### ISSUE THREAD

**Issue by PragneshHadiyel** [openanthem/nimbus-core#525]
#Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
We have a `@Grid` with `lazyLoad = true` and the filter is not working on the grid

**Sample Code**
```java
@Grid(pageSize = "7", pagination = true, lazyLoad=true)
@Config(when = "findStateByPath('/…/…/vsSearchBody/vfSearch/labelName') != null", url = "<!#this!>/…/searchResults.m/_process?fn=_set&url=/p/collection/_search?fn=query&<!page=y!>where=collection.labelName.containsIgnoreCase('<!/…/…/vsSearchBody/vfSearch/labelName!>')")
@Label("Search Results")
@MapsTo.Path(linked = false)
private List searchResults;

@Path
@GridColumn(sortable = true, filter = true, filterMode = FilterMode.contains)
@Label("Label Name")
private String labelName;
```

Please let me know if you need any other details.

### Code Snippet

# Environment Details
* **Nimbus Version:**
NIMBUS 1.3.0.M5

* **Browser:**
Google Chrome

**Comment by lopezton-anthem** [comment]
@PragneshHadiyel, server-side pagination requires the filter criteria to be sent so that the framework can pass it along to Spring to handle the server side filtering. You should just need to add `<!filterCriteria!>` to the `where` clause. I don't think you will need the `collection.labelName.containsIgnoreCase('...')` any longer, since `<!filterCriteria!>` handles building that for you.

Here's the `@Config` to try:

```java
@Config(when = "findStateByPath('/…/…/vsSearchBody/vfSearch/labelName') != null", url = "<!#this!>/…/searchResults.m/_process?fn=_set&url=/p/collection/_search?fn=query&<!page=y!>&where=<!filterCriteria!>")
```

Please follow up with your findings.

**Comment by PragneshHadiyel** [comment]
@lopezton-anthem 
We tried as suggested but still the same error is occurring. If need be we can schedule a call to discuss further.

**Comment by lopezton-anthem** [comment]
Worked with @PragneshHadiyel and team to resolve this. The configuration being used was incorrect.

Before I close this story I am going to add some thorough documentation for how `<!filterCriteria!>` and `<!page=y!>` work.
