### ISSUE TITLE
Adding entries in @PickList is only adding one entry

### ISSUE THREAD

**Issue by lopezton-anthem** [openanthem/nimbus-core#547]
# Issue Details 

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
When a `@PickList` is configured, adding entries from left to right is only adding one entry on the server side. e.g. if two two entries ["A", "B"] are in the left hand side, clicking add "A" and then add "B" will add the two entries in the picklist to the right side... but the network tab will show that "A" was added in both network requests.

## Expected Behavior
The network tab should show both entries "A" and "B" added in each individual network request.

# Environment Details
* **Nimbus Version:**
1.3.1.M1

* **Browser:**
Google Chrome

**Comment by lopezton-anthem** [comment]
I took a look at the PrimeNG changes to`picklist.component.ts` from when **we thought** this was last working in 1.1.14.

From 1.1.14 to 1.3.1.M1, the PrimeNG version changed from 6.1.7 to 7.1.0.  Searching [this Github diff](https://github.com/primefaces/primeng/compare/7fdcb1bc8aaf6e13c956c92c3aae49ca279f4106...master) for picklist.component.ts shows the difference... I don't think anything changed from PrimeNG's perspective that would have caused this issue.

**Comment by kumarraman** [comment]
There is one more issue with the picklists, the filter atop a picklist does not work.

**Comment by lopezton-anthem** [comment]
> There is one more issue with the picklists, the filter atop a picklist does not work.

@kumarraman, I'm not sure that these two issues would be related. Unless you think otherwise, can you please open a separate issue for this and outline how to reproduce the issue?

**Comment by lopezton-anthem** [comment]
Added in 1.3.1.M4
