### ISSUE TITLE
High Response time on certain submits functions

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#549]
Please reach out to the team for more details, we can share perf test results.

# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

### Code Snippet

# Environment Details
* **Nimbus Version:**

* **Browser:**

**Comment by lopezton-anthem** [comment]
I spoke with the team and asked them to review this and if needed, to schedule time with one of the framework team members to help identify the possible root causes.
