### ISSUE TITLE
Last updated date and Last Update By getting updated for few of the previously completed assessments

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#552]
Last updated date and Last Update By getting updated for few of the previously completed assessments

**Comment by lopezton-anthem** [comment]
This is likely a duplicate of #535. Please review and follow up.

**Comment by lopezton-anthem** [comment]
I spoke with the team on this and asked them to investigate if any `setState` methods were being invoked on the core, similar to what was suggested for #535.
