### ISSUE TITLE
Rendering issue in different resolution screens

### ISSUE THREAD

**Issue by soumyal2019** [openanthem/nimbus-core#580]
# Issue Details

The current application, when opened in a lower resolution screen (laptop) places the 4 columns tab within the prescribed space whereas when opened in a higher resolution screen (Monitor) there exist white spaces to the right side of the screen and appears to be a 6 columns tab.
```
[X ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
 
The current application, when opened in lower resolution screen (laptop) places the 4 columns tab within the prescribed space whereas when opened in a higher resolution screen (Monitor) there exist white spaces to the right side of the screen and appears to be a 6 columns tab. The look and feel of the application with these extra white spaces is not consistent and does not look good.

## Expected Behavior

The display should look same in lower and higher resolution screens.

### Steps to Reproduce

Please list the steps required to reproduce the issue (if any)

### Code Snippet

# Environment Details
* **Nimbus Version:**
Nimbus Version is 1.3.1.M1 

* **Browser:**
Google Chrome

@lopezton-anthem @sandeepmantha

**Comment by sandeepmantha** [comment]
**@CardDetail(cssClass="oneColumn") -** **Needs to be configured**
When we specify the oneColumn to the card detail control, it specifies that the card details needs to align with the size of the screen and use the one column layout
@CardDetail.Body(cssClass="fourColumn")
The four column to the body forces the fields to align in a 4 column layout and the parent container having one column makes sure that the width automatically adjusts based on the full width of the parent container.
