### ISSUE TITLE
Penalty Amount which is of type Double is not sorted correctly when used sortable = true on GridColumn

### ISSUE THREAD

**Issue by AGO3876** [openanthem/nimbus-core#601]
Penalty Amount which is of type Double is not sorted correctly when used sortable = true on GridColumn.

## Current Behavior 

0.00
0.00
120
190
4375
790.35

## Expected Behavior
0.00
0.00
120
190
790.35
4375

@Path("/penalty")
	@GridColumn(sortable = true,placeholder ="0.00")
	@Label("Penalty")
	private Double penalty;

Made change as below , but that didn't not change the current behavior.

@GridColumn(sortable = true,  sortAs = SortAs.NUMBER,placeholder ="0.00")

**Comment by AGO3876** [comment]
Any update on the issues ?

**Comment by sandeepmantha** [comment]
Cannot replicate the issue with 1.3.2.x version.
