### ISSUE TITLE
Merge https://github.com/openanthem/nimbus-core/issues/566 into 1.3.1.M4

### ISSUE THREAD

**Issue by addulaajayreddy** [openanthem/nimbus-core#603]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Merged https://github.com/openanthem/nimbus-core/issues/566 into 1.3.2.M1.

## Expected Behavior
Please get https://github.com/openanthem/nimbus-core/issues/566 merged into 1.3.1.M4

### Code Snippet

# Environment Details
* **Nimbus Version:**
1.3.1.M2

* **Browser:**
Google Chrome

**Comment by lopezton-anthem** [comment]
1.3.1.M4 was released. I would suggest that we put this into either 1.3.1.M5 or 1.3.1, as 1.3.2.M1 has already been released. (This change is in 1.3.2.M1)

**Comment by addulaajayreddy** [comment]
1.3.1.M5 should work.We see some issues in 1.3.2.M1 which are not in 1.3.1.M2 so we wanted this to be merged into a patch version.

**Comment by lopezton-anthem** [comment]
This change was pushed into `1.3.1.M5`.
