### ISSUE TITLE
Action menu doesn't close when selecting the contact from correspondence

### ISSUE THREAD

**Issue by AG32375** [openanthem/nimbus-core#608]
Vlad had a conversation with F/W a while back and they said that this is not a defect because when the link is clicked, there is no change on the UI so the link menu remains open.

Need confirmation if this issue can be addressed with the new framework

**Comment by lopezton-anthem** [comment]
Hi @AG32375,

Will you please fill out the template or provide more details on how to replicate this with configuration so that we can take a look?

**Comment by AG32375** [comment]
Hi Tony, Where can I get the template?

**Comment by AG32375** [comment]
Hi @lopezton-anthem,

This defect is regarding the closing of a @LinkMenu. We have a @LinkMenu, inside of which, we have 3 @Links. One of the links is also annotated with a single @Config which calls “<!#this!>/../../_process?fn=_setByRule=”. When clicking the link on the UI the rule is executed are expected however, the LinkMenu remains open. We would like for the LinkMenu to close when this link is clicked. Is there a way to have the LinkMenu close after the link is clicked and the rule is executed?

**Comment by lopezton-anthem** [comment]
This change is deployed in `1.3.2.M2`
