### ISSUE TITLE
Feature Request - AllArgsConstructor for native Domain Entities. 

### ISSUE THREAD

**Issue by thejeff77** [openanthem/nimbus-core#609]
#5 Issue Details

Please add param constructors for native domain entities such as Phone and Address

This can be accomplished by including the following annotations on domain entities

```
@AllArgsConstructor
@NoArgsConstructor
```

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[X] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Domain entity creation often results in an unnecessary amount of code individually setting every field. 

## Expected Behavior

`Phone phone = new Phone(Type.CELL, "308-456-7890", "7365")`

### Steps to Reproduce

Construct a native Nimbus entity.

### Code Snippet

See Current Behavior section

# Environment Details
* **Nimbus Version:**
1.3.1.M4

* **Browser:**
N/A

**Comment by lopezton-anthem** [comment]
I'm not sure if we we were ever planning on removing these objects entirely from the core framework library or not. @soham-anthem @jayantchaudhuri any guidance? If not, I don't think it's a big deal to add this in.

**Comment by thejeff77** [comment]
They seem to be used quite frequently, so if they aren't cumbersome to maintain - I'd vote to keep them in.

**Comment by lopezton-anthem** [comment]
Perhaps these would be a good candidate for their own project when we start splitting out nimbus-core.

We can consider adding these to a `domain-entity-common` or similar project.

**Comment by lopezton-anthem** [comment]
This change is deployed in `1.3.2.M2`

**Comment by thejeff77** [comment]
Awesome thanks!
