### ISSUE TITLE
Accordions are not rendering across the screen

### ISSUE THREAD

**Issue by ramank21** [openanthem/nimbus-core#628]
![Capture](https://user-images.githubusercontent.com/55709716/65455790-f9e93300-de15-11e9-93d3-c3f19cdd1dca.PNG)
When creating an assessment using the admin builder and when there is not enough content, the corresponding accordions do not show up across the screen

**Comment by sandeepmantha** [comment]
**@Accordion(cssClass = "oneColumn") - Needs to be configured**
This would ensure that the accordion is as wide as its parent container.
