### ISSUE TITLE
Multi-tenancy to support connecting multiple DB’s thought configuration

### ISSUE THREAD

**Issue by PragneshHadiyel** [openanthem/nimbus-core#645]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[X] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Expected Behavior

- Support to do CRUD b/w multiple DBs using config

**Note**: if it is already supported by current version of f/w please provide docs for how to use it.

### Code Snippet

# Environment Details
* **Nimbus Version:**

* **Browser:**
Google Chrome

**Comment by lopezton-anthem** [comment]
You can use `@Repo(value = Database.rep_custom, ...)` for this.

See: https://openanthem.github.io/nimbus-docs/latest/fundamentals.html#configuration-data-source-custom

**Comment by lopezton-anthem** [comment]
Closing this issue. Please add a comment if you encounter any bugs, otherwise please consider moving dicussion on how to use `rep_custom` to Discourse.
