### ISSUE TITLE
Calendar cannot switch months

### ISSUE THREAD

**Issue by anthonyng619** [openanthem/nimbus-core#648]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior

Whenever the user opens a calendar and switches months, it will briefly switch and then the calendar will close.

## Expected Behavior

The month should switch and the calendar should stay open to let the user select the date.

### Steps to Reproduce

1. Open up calendar picker.
2. Try to change month.

### Code Snippet

# Environment Details
* **Nimbus Version:**

1.3.2.M2
1.3.2.BUILD-SNAPSHOT

* **Browser:**

Chrome

**Comment by lopezton-anthem** [comment]
This is deployed in 1.3.2.M2
