### ISSUE TITLE
Textbox cannot be set to empty for BigDecimal

### ISSUE THREAD

**Issue by anthonyng619** [openanthem/nimbus-core#650]
# Issue Details

**Type of Issue**  (check one with "X")
```
[x] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior

A textbox cannot change state back to empty state if the type is BigDecimal.
If I enter '5' in for the textbox and submit it, it will save in the mongo database.
However, if I go back and edit the textbox to remove the '5' to become an empty box, it does not save in the mongo database.

## Expected Behavior

It should save and remove the '5' from the database.

### Steps to Reproduce

1. Create a textbox with BigDecimal type.
2. Map to a domain.
3. Submit a number inside the textbox.
4. Remove number and submit again.

### Code Snippet

# Environment Details
* **Nimbus Version:**

1.3.2.M2

* **Browser:**

**Comment by vivek-anthem** [comment]
fixed in the implementation code
