### ISSUE TITLE
Grid header "Showing 1-0 of 0"

### ISSUE THREAD

**Issue by anthonyng619** [openanthem/nimbus-core#655]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior

When clearing the grid, I am able to clear the items, but the remaining issue is the header displaying "Showing 1-0 of 0"

This is happening after I used server side pagination inside a function handler.

## Expected Behavior

When using setPage method, and an empty list or null is passed in, the header should display
"Showing 0-0 of 0" instead of "Showing 1-0 of 0".

### Steps to Reproduce

1. Set up a grid to be filled in with two pages of records.
2. Create a clear button that will get the grid param(/.m).
3. Use the setPage(List<T>, Pageable, Supplier) method on that param. In my case, I used setPage(new ArrayList<T> (or null), null, () -> 0l)
4. Go to the second page of the grid.
5. Hit the clear button and the header resets back to "Showing 1-0 of 0"

### Code Snippet

# Environment Details
* **Nimbus Version:**

1.3.2.M2

* **Browser:**

Chrome

**Comment by sandeepmantha** [comment]
Is this still an issue ?

**Comment by anthonyng619** [comment]
Yeah it's still an issue. I'm unable to set numberOfElements or totalElements for the page. PageRequest minimum page size allowed is 1. If I do PageRequest.of(0,0), there will be an exception.
