### ISSUE TITLE
Gaps on hidden fields

### ISSUE THREAD

**Issue by DragonLotus** [openanthem/nimbus-core#661]
# Issue Details

**Type of Issue**  (check one with "X")
```
[x] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior

Hidden fields still show up as empty fields within an accordion.

## Expected Behavior

Hidden fields shouldn't take up any space.

### Steps to Reproduce

Call the deactivate method on a param.

### Code Snippet

param.deactivate();

# Environment Details
* **Nimbus Version:**

1.3.1.M5

* **Browser:**

Chrome

**Comment by sandeepmantha** [comment]
Fixed in version 1.3.1.M6
