### ISSUE TITLE
Issue in the search grid - HIP application

### ISSUE THREAD

**Issue by anishkgs** [openanthem/nimbus-core#663]
We have  a search functionality in HIP application which is built on top of NIMBUS. We have used @ViewConfig.Grid to display the sub rows in search results. After each search when we expand the sub row and then clear the results and search again - results are not getting rendered into UI. This is the exceptional scenario and back end logic is working and results are fetched and set to the front end but not get displayed. We can see this results when we go to some other screen and come back to member search. Please help us on resolving this issue

**Comment by jvesole** [comment]
Team is not able to reproduce issue. A demo is needed.
