### ISSUE TITLE
Required Component - MaskedField 

### ISSUE THREAD

**Issue by PragneshHadiyel** [openanthem/nimbus-core#665]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[X] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Expected Behavior

We have a requirement to show masked data for HIPPA compliant values like SSN, Medicare Id or Medicaid Id. Right now, teams are writing rule files to mask data but the draw back with this is value gets stored in db in masked format when postChanges is set to true.

-> The new UI element you are going to build should be capable to mask certain characters on UI and clear data need to be sent when stored in mongodb.

Ex: 666-12-2222 should show as XXX-XX-2222 to user but stored it as 666-12-2222

Either add this capability to Text Field or Provide altogether new UI element.

### Code Snippet

# Environment Details
* **Nimbus Version:**

* **Browser:**
Google Chrome, MongoDB

**Comment by sandeepmantha** [comment]
Will be available in the version of 1.3.2.M3(when released)
