### ISSUE TITLE
Tag all releases

### ISSUE THREAD

**Issue by thejeff77** [openanthem/nimbus-core#677]
As a developer, I'd like to checkout the release of nimbus-core that my project is using in order to debug framework issues. 

# Issue Details

1.3.1.M5, and 1.3.1.M6 are missing from the release list and have not been tagged.

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

# Environment Details
* **Nimbus Version:**
1.3.1.M5, 1.3.1.M6

**Comment by sandeepmantha** [comment]
Tags are available in git now.

**Comment by thejeff77** [comment]
Thanks!
