### ISSUE TITLE
Text Box  filed is not accepting second decimal values as zero for BigDecimal data type when enter and type first time only

### ISSUE THREAD

**Issue by kchsravanthi** [openanthem/nimbus-core#692]
Text Box  filed is not accepting second decimal values as zero for BigDecimal data type when enter and type first time only.

Nimbus version : 1.3.2.M2
## Current Behavior
If enter 328.10 for Text box  it accepts 328.1 first time only .If change the value next time with second decimal 0 it keeps 328.10
## Expected Behavior
If enter 328.10 for Text box  it should accept the UI value as 328.10  

Reproduce.
1)Declare  a field with BigDecimal
2)Enter text field value 328.10
3)Click on anywhere in UI
4)Check the value in TextBox shows 328.1

**Comment by sandeepmantha** [comment]
Works as expected
