### ISSUE TITLE
Accordion Section does not render across the screen

### ISSUE THREAD

**Issue by PragneshHadiyel** [openanthem/nimbus-core#699]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Currently when the content in the Accordion Label is not enough to cover the entire width of the screen, the Accordion section does not render across the screen.

## Expected Behavior
The Accordion section must render across the available UI real estate

### Code Snippet

# Environment Details
* **Nimbus Version:**
1.3.2.M2

* **Browser:**
Google Chrome

**Comment by sandeepmantha** [comment]
nm-accordion {flex-basis:100%;}
Please override the css by pasting the above in the app_styles.css
