### ISSUE TITLE
Unable to set data in a text box 

### ISSUE THREAD

**Issue by Af73332** [openanthem/nimbus-core#702]
when an accordion is activated through the activateConditional  and there is a text box in the accordion , we cannot set the data in text box based on the condition, however the data is present in the DB.

Consider this example:
![dfds](https://user-images.githubusercontent.com/48531301/73965132-9271e280-48e1-11ea-81ac-010a904a423a.png)

**Comment by sandeepmantha** [comment]
Available in 1.3.2.M2
