### ISSUE TITLE
Retain grid page on refresh 

### ISSUE THREAD

**Issue by addulaajayreddy** [openanthem/nimbus-core#730]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ X ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Grid currently resets to page 1 on reload. 

## Expected Behavior
Retain the page where it was left.

### Steps to Reproduce
Click edit on a grid which navigates to a different page. On submitting the edited form it brings back to grid page 1.

### Code Snippet

# Environment Details
* **Nimbus Version:**
1.3.1.M6

* **Browser:**
Chrome

**Comment by jayantchaudhuri** [comment]
The changes are available in 1.3.1.M15 version
