### ISSUE TITLE
Timer functionality

### ISSUE THREAD

**Issue by addulaajayreddy** [openanthem/nimbus-core#731]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ X ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
No implementation 

## Expected Behavior
Need timer to be shown on UI and persist the time on exit of case 

### Code Snippet

# Environment Details
* **Nimbus Version:**
1.3.1.M6

* **Browser:**
Chrome

**Comment by jayantchaudhuri** [comment]
The changes are available in 1.3.1.M15 version
